name: Feature request
description: Suggest an idea or improvement
title: "[feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: What problem does this solve?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Proposed solution
    validations:
      required: true
